name: Docker Hub Release


on:
  push:
    tags:
      - "v*"


jobs:
  docker:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: decrypt secret
        run: |
          echo "Decrypting secrets..."
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DECRYPT_ENV_KEY }}" --output ./.env.prod ./.env.prod.gpg
          echo "Decrypting secrets...done"

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Generate Tags
        uses: docker/metadata-action@v3
        id: metadata
        with:
          images: |
            zmdyy0318/qqrobot
          tags: |
            type=semver,pattern={{version}}
            type=sha


      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
